(()=>{"use strict";
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function reveal(){const els=$$('.reveal,.tile');if(reduce||!('IntersectionObserver'in window)){els.forEach(el=>el.classList.add(el.classList.contains('tile')?'revealed':'is-visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add(e.target.classList.contains('tile')?'revealed':'is-visible');io.unobserve(e.target)}}),{threshold:.07,rootMargin:'0px 0px -16px 0px'});els.forEach(el=>io.observe(el))}
function tilt(){if(reduce||!matchMedia('(hover:hover) and (pointer:fine)').matches)return;$$('.tile').forEach(tile=>{tile.addEventListener('pointermove',e=>{const r=tile.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tile.style.transform=`perspective(900px) rotateX(${-y*5}deg) rotateY(${x*6}deg) translateY(-3px)`});tile.addEventListener('pointerleave',()=>tile.style.transform='')})}
function enquiry(){$$('[data-whatsapp-enquiry]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f);const msg=`Hello Kamal,\n\nName: ${d.get('name')||''}\nPhone: ${d.get('phone')||''}\nTopic: ${d.get('topic')||''}\nMessage: ${d.get('message')||''}\n\nI reached you through InvestWithKamal.`;window.open(`https://wa.me/${f.dataset.phone}?text=${encodeURIComponent(msg)}`,'_blank','noopener')}))}
function articleFilter(){const root=$('[data-article-index]');if(!root)return;const cards=$$('[data-article-card]',root),input=$('#articleSearch'),chips=$$('[data-filter]'),status=$('#articleStatus'),empty=$('#articleEmpty');let cat='all';function run(){const q=(input?.value||'').trim().toLowerCase();let n=0;cards.forEach(card=>{const hay=(card.dataset.search||'').toLowerCase(),okCat=cat==='all'||card.dataset.category===cat,okQ=!q||hay.includes(q),show=okCat&&okQ;card.hidden=!show;if(show)n++});if(status)status.textContent=n?`${n} matching article${n===1?'':'s'}`:'No matching articles';if(empty)empty.style.display=n?'none':'block'}input?.addEventListener('input',run);chips.forEach(ch=>ch.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));ch.classList.add('active');cat=ch.dataset.filter;run()}));const qp=new URLSearchParams(location.search).get('q');if(qp&&input){input.value=qp}run()}
function closeNav(){const nav=$('#mainNav');if(!nav)return;$$('.nav-link',nav).forEach(a=>a.addEventListener('click',()=>{if(nav.classList.contains('show')&&window.bootstrap){bootstrap.Collapse.getOrCreateInstance(nav).hide()}}))}
function boot(){reveal();tilt();enquiry();articleFilter();closeNav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
